apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee-container
          image: acrlndqa.azurecr.io/laukendrasingh/employee:$(Build.BuildId)
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: $(SPRING_PROFILES_ACTIVE)

---
apiVersion: v1
kind: Service
metadata:
  name: employee-loadbalancer
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: employee-clusterip
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msv-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: alert-clusterip
                port:
                  number: 80
            path: /alert(/|$)(.*)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: employee-clusterip
                port:
                  number: 80
            path: /employee(/|$)(.*)
            pathType: ImplementationSpecific
